# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# example prompt format
#format = '''
#[test](cyan)
#[random shit](blue)
#[>](white)'''

# configure the character module more thoroughly
[character]
success_symbol = '[❯](white)'
error_symbol = '[❯](red)'

[directory]
style = 'blue'

# disable command duration module
[cmd_duration]
disabled = true

# disable the line break module so the prompt isn't split into two lines
[line_break]
disabled = true

# disable showing environment variables in the prompt
[env_var]
disabled = true
